version: "3.7"
services:
  oauth-as:
      image: oauth-as:latest
      container_name: oauth-as
      expose:
        - 8081
      ports:
        - 8081:8081
      restart: unless-stopped
      environment:
        - SPRING_PROFILES_ACTIVE=dev
      volumes:
        - oauth-as-data:/logs
  oauth-ca:
    image: oauth-ca:latest
    container_name: oauth-ca
    expose:
      - 8082
    ports:
      - 8082:8082
    restart: unless-stopped
    depends_on:
      - oauth-as
    links:
      - oauth-as
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - oauth-ca-data:/logs
volumes:
  oauth-as-data:
  oauth-ca-data:
